### ISSUE TITLE
Support for another syntax

### ISSUE THREAD

**Issue by MDanialSaleem** [skovy/font-awesome-codemod#4]
Will it be possible to add support for the following syntax?
```
<FontAwesomeIcon icon={['far', 'lightbulb']} />
```

Thanks.

**Comment by skovy** [comment]
I believe it does already?

Here's the test case: https://github.com/skovy/font-awesome-codemod/blob/ef654603386e436994536c247281d06bc5f7054f/transforms/__testfixtures__/implicit-icons-to-explicit-imports/array.input.tsx
